### PR TITLE
Rage Quit button w/video, button doesn't work yet

### PR DESCRIPTION
**Pull request by Marsha331**
Let me know if you guys like the video clip. I wanted to keep it short, but can maybe find a better one if you want. Button doesn't quit yet.

### CODE REVIEW

**Comment by Brandongoodman615** [comment]
This is hilarious! Good job! 👍

**Comment by ilyakrasnov** [comment]
😂 😂 😂  Looking forward to see the rest working!

**Comment by ilyakrasnov** [comment]
Just wondering @Marsha331 do we want to destroy the game for good? Maybe we could mark it as conceded somehow... Its up to you though - from the pr point of view its as clear 👍

**Comment by Marsha331** [comment]
I made it so there's a warning on it. If we make the save game feature and the score keeping feature,  I can change Rage Quit to just save and concede. For now, I'll keep it this way.

**Pull request merged**
