### PR TITLE
jquery ui gem install

### PR DESCRIPTION
**Pull request by saj528**

### CODE REVIEW

**Comment by ilyakrasnov** [comment]
@saj528 Looks great 👍 Let's add the drop part and communication with the controller in the same pr so that we don't break the master

**Comment by ilyakrasnov** [comment]
@saj528 @Marsha331 any progress on that one?

**Comment by Marsha331** [comment]
Pieces can now move and snap to the squares on the board.

**Comment by ilyakrasnov** [comment]
Nice work @Marsha331 ! now what's left is to send hit the controller action using ajax

**Pull request merged**
