### PR TITLE
Adding CRUD, Simple_form install, root show page, add resources for g…

### PR DESCRIPTION
**Pull request by saj528**
Adding CRUD, Simple_form install, root show page, add resources for game controller, Adding Game controller and model.

Whenever we have boot strap we need to run "rails generate simple_form:install --bootstrap"
So simple_form will use bootstrap.

### CODE REVIEW

**Comment by bhk1019** [comment]
Looks good except perhaps we may want to change the root directory from games#show to nothing in case we have a static landing page to set as our root later?

**Comment by Brandongoodman615** [comment]
Devise gem requires a root page which I didn't add because it was assigned in this pull, but that is a good point on the naming. Maybe static_pages#index like we did in Flixter.

**Comment by saj528** [comment]
Those sound like good ideas. The ticket did say though to make a Game controller and model with the new, create and show functions. So if we have a static_pages view that would require another controller which the ticket did not specify.

**Comment by bhk1019** [comment]
I suppose we can always change the root path to something else later if need be, and since Devise needs a root path set, it's probably best to just leave it as is. Thumbs up!

**Comment by ilyakrasnov** [comment]
👍 @saj528 if pr #2 is merged before yours, you'll need to do the following:

* switch to master locally
* pull master from github locally
* switch to your branch (the one of this pr)
* run `git merge master` (in order to incorporate the merged changes)
* run `rails generate simple_form:install --bootstrap` (in order to make it complete) 

Once everything is up and running locally you can push the branch, it'll update the pr

**Comment by ilyakrasnov** [comment]
@saj528 I've just pushed a small commit resolving the merge conflict. It would be great to add a simple "Add game" button so you can enter the name of the game and save it.

**Pull request merged**
